### ISSUE TITLE
bundle install --jobs causes creation of .bundle/config folder

### ISSUE THREAD

**Issue by AndreHoffmann-diconium** [maierj/fastlane-action#48]
The implementation of
`function installBundleDependencies(pathToGemFile, customInstallPath)`
contains the call 
`bundle install --jobs 2`

Bundler will create a configuration file after using this command, see [this issue](https://github.com/rubygems/bundler/issues/7042).

The problem is that this causes an unclean working copy. Tools to bump and commit the version number will fail because of this.

**Comment by maierj** [comment]
I'll leave the issue open for now, because the described behavior is not ideal. A fix will not be implemented with highest priority though. When committing a version bump, you should only track the changes in the necessary files, not `git add --all`. If you depend on another tool that is doing this, just add the `.bundle/config` file to your `.gitignore` (as long as the tool does not force-add the file, but then you should rethink, if you really want to use this tool).

**Comment by AndreHoffmann-diconium** [comment]
Thanks, this is how I resolved the issue, by adding the directory to the .gitignore.
