### ISSUE TITLE
Ensure Compatibility With Local Actions Via ACT

### ISSUE THREAD

**Issue by pacarvalho** [maierj/fastlane-action#49]
Debugging Github Actions can be made quicker by running the actions locally. One possible way to do that is by using https://github.com/nektos/act which (by default) uses node:12.6-buster-slim image. 

However, this Action seems to fail when run locally (possibly due to OS incompatibility) with the following error: 

```
[Deploy Android/deploy-android]   ⚙  ::add-path:: /bin
| /bin/sh: 1: sudo: not found
| /bin/sh: 1: fastlane: not found
[Deploy Android/deploy-android]   ❗  ::error::Error: Executing lane deploy_internal failed.
[Deploy Android/deploy-android]   ❗  ::error::Executing lane deploy_internal failed.
[Deploy Android/deploy-android]  
```

Running `act -P ubuntu-latest=nektos/act-environments-ubuntu:18.04` to use the alternative image seems to address the issue! However, the image is 18GB in size which can be quite slow to download and run. 

Would it be within the scope of this project to make it compatible with `act` by default? 

If not, let me know and I will close this issue. Either way, thank you for open sourcing this project and helping make our lives a bit easier!

**Comment by maierj** [comment]
This action depends on a few tools that are installed on GitHub Action Runners but which are not included in the node:12.6-buster-slim image, for example fastlane. Therefore, it only works with the alternative image, which includes those additional tools. That's what's also explained here: https://github.com/nektos/act#default-runners-are-intentionally-incomplete
If your question is, if it's possible to make the action compatible and testable with the default image that act uses, then the answer is: no, that's technically not possible.

Let me know if you meant something else. Otherwise, feel free to close the issue.
