### ISSUE TITLE
Fails to install fastlane due to older ruby version on ubuntu latest image.

### ISSUE THREAD

**Issue by mattjamesaus** [maierj/fastlane-action#52]
This currently fails on the standard 18 ubuntu box due to ruby version being too low, in our case upgrading to a new version of ruby fixed using 
` - name: Checkout
     uses: actions/setup-ruby@v1
     with:
          ruby-version: '2.7.1'`

in order to get it going again, maybe worth adding a ruby version check.

**Comment by maierj** [comment]
Currently, there's a hardcoded version spec for ruby: `>= 2.6`
Would it make sense to define an optional parameter to specify a ruby version, like in the `setup-ruby` action? The other option would be to require the user of the Fastlane action to prepend a `setup-ruby` step in his workflow, like you did.

**Comment by bobinrinder** [comment]
Just FYI: I had this issue:
```
/usr/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
	from /usr/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
	from /usr/local/bin/bundle:23:in `<main>'`
```
and fixed it with running this as a step before this fastlane step:
```
      - name: Ruby Setup for Fastlane
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
```

**Comment by maierj** [comment]
Thank you for your feedback. I decided that it shouldn't be the responsibility of this action to setup the correct Ruby version, especially since there is a dedicated action who's sole responsibility is exactly that. In the new version 2.0.0 that was just released, the implementation is depending on the Ruby version already being set up when it's executed. That means that every developer who uses it has to prepend a setup-ruby step, like you did.
